GET http://localhost:3000

###
POST http://localhost:3000/routes
Content-Type: application/json

{
  "name": "route test 1",
  "source_id": "ChIJRXBkA9AypwARwPAkMaZwonU",
  "destination_id": "Ei9Bdi4gSm92ZSBTb2FyZXMgLSBHcmHDp2FzLCBJdGHDum5hIC0gTUcsIEJyYXppbCIuKiwKFAoSCaF79ErQMqcAEfg4K4Ib5up0EhQKEgnTQT3LJTOnABEzDcpoMSmpTQ"
}

### Maps

### Get Place_id
GET http://localhost:3000/places?text=Itaúna - Avenida Getúlio Vargas - Centro, Itaúna - MG, Brasil


### Get Directions between 2 points
GET http://localhost:3000/directions?originId=ChIJRXBkA9AypwARwPAkMaZwonU&destinationId=Ei9Bdi4gSm92ZSBTb2FyZXMgLSBHcmHDp2FzLCBJdGHDum5hIC0gTUcsIEJyYXppbCIuKiwKFAoSCaF79ErQMqcAEfg4K4Ib5up0EhQKEgnTQT3LJTOnABEzDcpoMSmpTQ
